title: "My Blog Title"
subtitle: "My Blog Subtitle"
description: "My Description"

logo: "/assets/img/logo.png"

page_details:
  tags: true                # Generate tag detail pages
  categories: true          # generate category detail pages

social_networks:
  twitter: "@patmol6"
  github: "patmol"
  email: "evrardc@icloud.com"