title: "My Blog Title"
subtitle: "My Blog Subtitle"
description: "My Description"

logo: "/assets/img/logo.png"

page_details:
  tags: true                # generate tag and tags detail pages
  categories: true          # generate category and categories detail pages
  archives: true            # generate archives pages

social_networks:
  twitter: "@patmol6"
  github: "patmol"
  email: "evrardc@icloud.com"